#!/bin/bash

rm 0x*.bdd
rm search.bdd
rm task.txt
rm certificate.txt

#PDDL_FILE=~/pddls/unsolv-total/unsat-nomystery/nomystery-problem-05-9-9-1-01.pddl
#PDDL_FILE=~/pddls/unsolv-total/bag-gripper/prob24.pddl
PDDL_FILE=~/pddls/unsolv-total/bottleneck/prob03.pddl
#PDDL_FILE="/home/simsal00/pddls/unsolv-total/cave-diving/dom05.pddl /home/simsal00/pddls/unsolv-total/cave-diving/prob05.pddl"
#PDDL_FILE=~/pddls/unsolv-total/chessboard-pebbling/prob03.pddl
echo "-------------------------------------------------"
echo "RUNNING TASK"
echo "-------------------------------------------------"
./../../fast-downward.py --build "release32" $PDDL_FILE --search "astar(merge_and_shrink(merge_strategy=merge_precomputed(merge_tree=linear()), shrink_strategy=shrink_bisimulation(), label_reduction=exact(before_shrinking=true,before_merging=false)), generate_certificate=true)" 
#./../../fast-downward.py --build "release32" $PDDL_FILE --search "astar(hmax())"
#./../../fast-downward.py --build "release32" $PDDL_FILE --search "astar(hm())"
echo ""
echo "-------------------------------------------------"
echo "RUN VERIFIER"
echo "-------------------------------------------------"
./verify task.txt certificate.txt
