#!/bin/bash

rm cert*.txt
rm task.txt

#PDDL_FILE=clickgame/prob11.pddl
#PDDL_FILE=no-mystery/prob04.pddl
PDDL_FILE=../../sokoban_benchmarks/mode02-50set-easy/sokoban-mode02-6x6-3s-1.pddl

echo "-------------------------------------------------"
echo "RUNNING TASK"
echo "-------------------------------------------------"
./../fast-downward.py ../../benchmarks/$PDDL_FILE --search "astar(merge_and_shrink(merge_strategy=merge_linear(), shrink_strategy=shrink_bisimulation(), label_reduction=label_reduction(false,false)))"
echo ""
echo "-------------------------------------------------"
echo "RUNNING INSTANTIATE"
echo "-------------------------------------------------"
./translate/instantiate.py ../../benchmarks/$PDDL_FILE
echo ""
echo "-------------------------------------------------"
echo "RUN VERIFIER"
echo "-------------------------------------------------"
./verify task.txt certificate.txt
